validate:
  token:
     open: 0
     key: zhqyd0ic?gReoBP%9
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: PT2S
    lettuce:
       pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: PT2S
mybatis:
  type-aliases-package: com.tnaot.**.entity
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 50
      maximumSize: 10000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon: 
  ConnectTimeout: 20000
  ReadTimeout: 20000 
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 3000
management: 
  security:
    enabled: false
memcached:
  host: 47.52.144.242
  port: 22122
zuul:  
  okhttp:
    enabled: true
  ribbon-isolation-strategy: THREAD
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuulgw
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    max-total-connections: 10000
    max-per-route-connections: 5 
  routes:  
    api-login:
      path: /login
      serviceId: admin-sso
      stripPrefix: false
    api-admin:
      path: /admin/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-shop:  
      path: /shop/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-marketing:  
      path: /marketing/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-media:  
      path: /media/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-life:
      path: /life/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-system:
      path: /system/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-risk:
      path: /risk/**
      serviceId: tnaot-admin
      stripPrefix: false 
    api-push:
      path: /push/**
      serviceId: tnaot-admin
      stripPrefix: false 
    api-member:
      path: /member/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-user:
      path: /user/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-news:
      path: /news/**
      serviceId: admin-news
      stripPrefix: false  
    api-configuration:
      path: /configuration/**
      serviceId: admin-news
      stripPrefix: false  
    api-promotion:
      path: /promotion/**
      serviceId: admin-news
      stripPrefix: false
    api-block:
      path: /block/**
      serviceId: admin-news
      stripPrefix: false
    api-report:
      path: /report/**
      serviceId: admin-news
      stripPrefix: false