logging:
  config: classpath:logback-dev.xml
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  cloud:
    gateway:
      routes:
      - id: api-login
        uri: lb://admin-sso
        predicates:
        - Path=/login
        
      - id: api-logout
        uri: lb://admin-sso
        predicates:
        - Path=/logout
        
      - id: api-updatePassword
        uri: lb://admin-sso
        predicates:
        - Path=/update_password
        
      - id: api-admin
        uri: lb://admin-life
        predicates:
        - Path=/admin/**
        
      - id: api-shop
        uri: lb://admin-life
        predicates:
        - Path=/shop/**
        
      - id: api-marketing
        uri: lb://admin-life
        predicates:
        - Path=/marketing/**
        
      - id: api-media
        uri: lb://admin-news
        predicates:
        - Path=/media/**
        
      - id: api-life
        uri: lb://admin-life
        predicates:
        - Path=/life/**
        
      - id: api-system
        uri: lb://admin-life
        predicates:
        - Path=/system/**
        
      - id: api-risk
        uri: lb://admin-life
        predicates:
        - Path=/risk/**
        
      - id: api-push
        uri: lb://admin-life
        predicates:
        - Path=/push/**
        
      - id: api-member
        uri: lb://admin-life
        predicates:
        - Path=/member/**
        
      - id: api-user
        uri: lb://admin-life
        predicates:
        - Path=/user/**
        
      - id: api-news
        uri: lb://admin-news
        predicates:
        - Path=/news/**
        
      - id: api-configuration
        uri: lb://admin-news
        predicates:
        - Path=/configuration/**

      - id: api-promotion
        uri: lb://admin-news
        predicates:
        - Path=/promotion/**

      - id: api-block
        uri: lb://admin-news
        predicates:
        - Path=/block/**

      - id: api-report
        uri: lb://admin-news
        predicates:
        - Path=/report/**

      - id: api-log
        uri: lb://admin-news
        predicates:
        - Path=/log/**

      - id: api-statistic
        uri: lb://admin-news
        predicates:
        - Path=/statistic/**

      - id: api-hot-git
        uri: lb://admin-life
        predicates:
        - Path=/actuator/refresh

      discovery:
        locator:
          lower-case-service-id: true
          
  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: PT2S
    lettuce:
       pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: PT2S

eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 50
      maximumSize: 10000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon: 
  ConnectTimeout: 20000
  ReadTimeout: 20000 
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 3000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS