validate:
  token:
     open: 0
     key: zhqyd0ic?gReoBP%9
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: PT2S
    jedis:
       pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: PT2S
mybatis:
  type-aliases-package: com.tnaot.**.entity
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 50
      maximumSize: 10000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon: 
  ConnectTimeout: 20000
  ReadTimeout: 20000 
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 3000
management: 
  security:
    enabled: false
memcached:
  host: 47.52.144.242
  port: 22122
zuul:  
  okhttp:
    enabled: true
  ribbon-isolation-strategy: THREAD
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuulgw
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    max-total-connections: 10000
    max-per-route-connections: 5 
  routes:  
    api-admin:
      path: /admin/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-shop:  
      path: /shop/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-marketing:  
      path: /marketing/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-media:  
      path: /media/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-life:
      path: /life/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-system:
      path: /system/**
      serviceId: tnaot-admin
      stripPrefix: false
    api-risk:
      path: /risk/**
      serviceId: tnaot-admin
      stripPrefix: false 
    api-news:
      path: /news/**
      serviceId: admin-news
      stripPrefix: false  
    api-configuration:
      path: /configuration/**
      serviceId: admin-news
      stripPrefix: false  
    api-news1:
      path: /news1/**
      serviceId: admin-news
      stripPrefix: false 
    api-news2:
      path: /news2/**
      serviceId: admin-news
      stripPrefix: false
    api-news3:
      path: /news3/**
      serviceId: admin-news
      stripPrefix: false
    api-news4:
      path: /news4/**
      serviceId: admin-news
      stripPrefix: false
    api-news5:
      path: /news5/**
      serviceId: admin-news
      stripPrefix: false
    api-news6:
      path: /news6/**
      serviceId: admin-news
      stripPrefix: false
    api-news7:
      path: /news7/**
      serviceId: admin-news
      stripPrefix: false
    api-news8:
      path: /news8/**
      serviceId: admin-news
      stripPrefix: false
    api-news9:
      path: /news9/**
      serviceId: admin-news
      stripPrefix: false
    api-news10:
      path: /news10/**
      serviceId: admin-news
      stripPrefix: false
    api-news11:
      path: /news11/**
      serviceId: admin-news
      stripPrefix: false
    api-news12:
      path: /news12/**
      serviceId: admin-news
      stripPrefix: false
    api-news13:
      path: /news13/**
      serviceId: admin-news
      stripPrefix: false
    api-news14:
      path: /news14/**
      serviceId: admin-news
      stripPrefix: false
    api-news15:
      path: /news15/**
      serviceId: admin-news
      stripPrefix: false
    api-news16:
      path: /news16/**
      serviceId: admin-news
      stripPrefix: false
    api-news17:
      path: /news17/**
      serviceId: admin-news
      stripPrefix: false
    api-news18:
      path: /news18/**
      serviceId: admin-news
      stripPrefix: false
    api-news19:
      path: /news19/**
      serviceId: admin-news
      stripPrefix: false
    api-news20:
      path: /news20/**
      serviceId: admin-news
      stripPrefix: false