validate:
  token:
     open: 1
     key: zhqyd0ic?gReoBP%9
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: PT2S
    lettuce:
       pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: PT2S
  servlet:
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 2000
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 240001
ribbon: 
  ConnectTimeout: 60000
  ReadTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 3000
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
memcached:
  host: 47.52.144.242
  port: 22122
zuul:  
  okhttp:
    enabled: true
  ribbon-isolation-strategy: THREAD
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuulgw
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 60000
    max-per-route-connections: 5 
  routes:  
    api-home:
      path: /home/**
      serviceId: tnaot-sso
      stripPrefix: false
     
    api-bindMobile:  
      path: /user/bind_mobile
      serviceId: tnaot-sso
      stripPrefix: false
    api-updatePwd:  
      path: /user/update_pwd
      serviceId: tnaot-sso
      stripPrefix: false
    api-uploadHeadImg:  
      path: /user/update_head_img
      serviceId: tnaot-sso
      stripPrefix: false

    api-search:  
      path: /search/**
      serviceId: tnaot-search
      stripPrefix: false
      
      
    api-user:  
      path: /user/**
      serviceId: tnaot-news
      stripPrefix: false
    api-media:  
      path: /media/**
      serviceId: tnaot-news
      stripPrefix: false
    api-news:
      path: /news/**
      serviceId: tnaot-news
      stripPrefix: false
    api-article:
      path: /article/**
      serviceId: tnaot-news
      stripPrefix: false
    api-action:
      path: /action/**
      serviceId: tnaot-news
      stripPrefix: false
    api-common:
      path: /common/**
      serviceId: tnaot-news
      stripPrefix: false
    api-channel:
      path: /channel/**
      serviceId: tnaot-news
      stripPrefix: false
    api-rank:
      path: /rank/**
      serviceId: tnaot-news
      stripPrefix: false
      
    api-mission:
      path: /mission/**
      serviceId: tnaot-marketing
      stripPrefix: false
    api-mentor:
      path: /mentor/**
      serviceId: tnaot-marketing
      stripPrefix: false
    api-wallet:
      path: /wallet/**
      serviceId: tnaot-marketing
      stripPrefix: false
      
    api-life: 
      path: /life/**
      serviceId: tnaot-life
      stripPrefix: false
      sensitiveHeaders:
    api-report:
      path: /report/**
      serviceId: tnaot-life
      stripPrefix: false
    api-member:
      path: /member/**
      serviceId: tnaot-sso
      stripPrefix: false
      
      
    api-shop:
      path: /shop/**
      serviceId: tnaot-shop
      stripPrefix: false
    api-campaign:
      path: /campaign/**
      serviceId: tnaot-shop
      stripPrefix: false
      