spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: 2000
    pool:
      max-active: 8 
      max-idle: 8
      min-idle: 1
      max-wait: 2000
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
management: 
  security:
    enabled: false