logging:
  config: classpath:logback-dev.xml
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .ftl
    template-loader-path:
    - classpath:/templates/
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.1.170:3306/mongcent_news?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: dbuser
    password: asdQWE!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      aop-patterns: false
      initial-size: 2
      min-idle: 2
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: select 'x'
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: 2000
    pool:
      max-active: 8 
      max-idle: 8
      min-idle: 1
      max-wait: 2000
  data:
    mongodb:
      uri: mongodb://test:123456@192.168.1.112:27017/tnaot
  rabbitmq:
    host: 192.168.1.112
    port: 5672
    username: rabbit
    password: 123456
    publisher-confirms: true
    virtual-host: /
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/messages
mybatis:
  type-aliases-package: com.tnaot.**.entity
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
management: 
  security:
    enabled: false
ftp:
  host: 192.168.1.136
  port: 21
  username: upload
  password: wenjianshangchuan
  basePath: /home/upload
  fileServerPath: http://47.52.144.242:7003
  imageFolder: image
  thumbFolder: thumbs
  videoFolder: video
path:
  defaultImage: http://refile.tnaot.com/image/2018/10/24/252a9b16113841d5992cb67a925971c2.jpg
  ipDistrictUrl: http://192.168.1.136:8074/json/
tm:
  manager:
    url: http://127.0.0.1:8899/tx/manager/
fdfs:
  so-timeout: 1501 #socket连接超时时长
  connect-timeout: 2000 #连接tracker服务器超时时长
  file-server-path: http://120.78.77.65:8888
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 120.78.77.65:22122
big-data:
  path: 
    token: cd85279322a1fd81a2caeb7a7b4285ac
  # 推荐资讯接口地址
    recomment-news-api: http://219.135.171.94:7025/news/channel
  # 推荐搜索关键词接口地址
    recomment-keyword-api: http://219.135.171.94:7025/word/searchword
  # 相关资讯接口地址
    recomment-relate-news-api: http://219.135.171.94:7025/news/relevant
  # 资讯内容去重格式化(用于爬虫添加/修改接口)
    news-content-reformat-api: http://219.135.171.94:7024/news-content/format
seaweedfs:
      host: 192.168.1.137
      port: 9333
      timeout: 50000
      maxConnection: 100
logging:
    level:
       org:
          apache:
            http:
              impl:
                conn: ERROR
       net:
          anumbrella:
             seaweedfs:
               core:
                Connection: ERROR