logging:
  config: classpath:logback-dev.xml
spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.1.170:3306/mongcent_shop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

bmb:
   front:
       url: 127.0.0.1:8090/bmb/front/
