logging:
  config: classpath:logback-test.xml
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://47.52.144.242:3306/mongcent_news?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true
    username: dbuser
    password: asdQWE!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: select 'x'
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.1.136
    port: 6380
    password: 123456
    timeout: 2000
    pool:
      max-active: 8 
      max-idle: 8
      min-idle: 1
      max-wait: 2000
  rabbitmq:
    host: 192.168.1.136
    port: 5671
    username: rabbit
    password: 123456
    publisher-confirms: true
    virtual-host: /
    listener: 
      simple:
        acknowledge-mode: manual
  data:
    mongodb:
      uri: mongodb://admin:123456@192.168.1.136:27018/admin
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/messages
mybatis:
  type-aliases-package: com.tnaot.**.entity
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 50
      maximumSize: 10000
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: -1
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon: 
  ConnectTimeout: 20000
  ReadTimeout: 20000 
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 3000
management:
  context-path: /news
  security:
    enabled: false
ftp:
  host: 47.91.221.83
  port: 21
  username: ftpuser
  password: ftpuser20180620
  basePath: /
  fileServerPath: http://47.52.144.242:7003
  imageFolder: image
  thumbFolder: thumbs
  videoFolder: video
path:
  defaultImage: http://refile.tnaot.com/image/2018/10/24/252a9b16113841d5992cb67a925971c2.jpg
  ipDistrictUrl: http://192.168.1.136:8074/json/
fdfs:
  pool:
    max-total: 150
  so-timeout: 1501 #socket连接超时时长
  connect-timeout: 2000 #连接tracker服务器超时时长
  file-server-path: http://47.52.150.234:8888
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 47.52.150.234:22122
big-data:
  path: 
    token: cd85279322a1fd81a2caeb7a7b4285ac
  # 推荐资讯接口地址
    recomment-news-api: http://219.135.171.94:7025/news/channel
  # 推荐搜索关键词接口地址
    recomment-keyword-api: http://219.135.171.94:7025/word/searchword
  # 相关资讯接口地址
    recomment-relate-news-api: http://219.135.171.94:7025/news/relevant
  # 资讯内容去重格式化(用于爬虫添加/修改接口)
    news-content-reformat-api: http://219.135.171.94:7024/news-content/format
    