logging:
  config: classpath:logback-dev.xml
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.1.170:3306/mongcent_shop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: dbuser
    password: asdQWE!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: select 'x'
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: PT2S
    jedis:
       pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: PT2S
  data:
    mongodb:
      uri: mongodb://test:123456@192.168.1.112:27017/tnaot
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/messages
  rabbitmq:
    host: 192.168.1.112
    port: 5672
    username: rabbit
    password: 123456
    publisher-confirms: true
    virtual-host: /
    listener: 
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
        retry: 
          max-attempts: 5  #最大重试次数
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          initial-interval: 5000 #重试间隔时间（单位毫秒）  
mybatis:
  type-aliases-package: com.tnaot.**.entity
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon: 
  ConnectTimeout: 20000
  ReadTimeout: 20000 
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 3000
management:
  context-path: /shop
  security:
    enabled: false
tx-lcn:
    client:
        manager-address: 192.168.1.112:8070
        chain-level: 3
        dtx-aspect-order: 0
        resource-order: 0
    ribbon:
        loadbalancer:
          dtx:
            enabled: true
payconfig:  
  alipay:
    app-id: 2018092561526368
    pay-url: https://openapi.alipay.com/gateway.do
    ras-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCP7ZP+ny+FE/kZGcMj7nyyqfc4mB3r11VInZoGMRPyi27q9A2YTZ+GQUbuINLG9emD4tZULMrQWfiz2h/LVqVW4dIYV3UPN04tdjrJf7pbIKiO2sr2XeSOlxlarfwOJHEeiDIWHPKnrazTByAy5gQ9JQIaNDn7uJDfMUbc51nuhenXe4BJjnjkouHtGldEYiURbDagBA3Q6zT9XXmPQUUqSHn290kMOYIxNWVVlT49Hfdy28Ik0sW/ynu1XliUqbbEgFGPKhgnvOgtSMs/aWBbhVZ3XNggsf0xlJEPd/3TlJtgl9lZdos/yE8V/TUPK6uUUtRyS9GQqJtRwJOyMcYzAgMBAAECggEAYjqLHuQV0oVnJLJodEV35ZgKmh13jlZQZlbpoAAu1QJEmSYngSK5FS/H8Q2FzTRYQyK1lI1dfgVpr5XWzTg9b6Z/dQ17Xv8n4+8lABCkZz1KzPSWQL6kFo0ZSMIlnKFScrwRMvZexgHKSdw7JYHGstRnMusiB6JXfXxsGKfswNSp0GTDGV/EqPW9hLK+RdTut7E5QF+bZq8ijVbCtoxzfqK9PLlWkHmE1VcXkEoZ1q0X0xqrsL7Ji5KHwpI5SRPsguR4URuy9bEdbmx/4t4ln6UWDYNEwUQlUe3ZSq+B9r6H4UarpEZzvGHC4w4B+V1LuOzSvpEPU+Hsh/Lnnx2TgQKBgQDnIQ0LF0JnP0ndxj3U1C2UOh7+6u0m2R7WLfooMPxk86nO7s+KXW1pBU7UZcjooIPU4IxwUdXFB6eVYQ2bfAN0+edScHCe2YP8QNhXzQSvFCB7haHz+rfHmJLUUIL34AhwlULxePKzkMps3k1/UcrJaNcj3VqluH4+Iy2hDY0U+wKBgQCfamLOxKog45sBWEPV87xNALG3ckeww9CHrE6TXSzHm4vfdkiCmUbHicoDIpz6Qq5KUHPdgOBfTbO1K3YUWV0aDeZzhtK5uJwr+8RjyoAd2sUF4N9fBF0qQNjUjXSy8qy674MrTkGt0TWoUGgdXH7YbV5pCq/MWTBErLkLuSweKQKBgCNQFGsWYanerI16xWWoCVK1UpkGEbe2wpRcr/TGDznpVI9uQz1Tquy5x+KBrqGELMAwkqRyjGOvGLak/mw8FVcg+2vIDBzpBNZcnfFEPKv3OkNFFoptSvju4bgYmPoAO6nf1DuKjCJNQ/BAQrzqJT6CiyRKpJffSUJ7I3SQ2nZTAoGABLvJ903Lp3Jate2DBiVYoAi3PjU8f7kwxfaN1r5biAnMW3RNruMSQPaMcw9iDeRQ/I/rANbE0s+h2G1T8kK9CvsCrseAFleu+3dcW4I1z60hUI1e1JlyksCeL6GLp4yhKGPYRz7poFmn+Dl6/fQzKAYHWaMhmTXEwyVF0V1MPBECgYBrG5iB46+jWm1ZRT6cDMJYupfkcH4CzfiLY/wY7894akSkkg6tnTarQh51Mq82epm8BEh1K2EM9RkS0T2bLh/bPkKa8O9ofeINmWSPE3LEepQ+yhb9GjsDAfy+C/XPhxuCPRdm8GRVKrWnQf76FOHwllSgg9H0qalKu+Zc/pyJjw==
    notify-url: http://rest.tnaot.com:8080/rest/shop/notify/payment/alipay
    timeout-express: 30
    seller-id: 2088231841236080
  tenpay:
    app-id: wxd4d3c645268d1b14
    app-secret: 746a6d3ca6f6499055effad514cd7538
    app-mch-id: 1515844081
    api-key: 1af3ecc644f4478aabaeb386fdedaa2b
    notify-url: http://rest.tnaot.com:8080/rest/shop/notify/payment/tenpay
    h5-id: wx3a4fb0286f7945aa
    h5-mch-id: 1515222121
  huione:
    app-id: 2f73c4cf27abee6e
    pay-url: https://open.huione.com/?_c=gateway&_a=orderPay
    front_fail_url: http://lifetest.tnaot.com/rechargeIndex/prepaidIndex/paymentFail
    front_success_url: http://lifetest.tnaot.com/rechargeIndex/prepaidIndex/paymentSuccess
    notify-url: http://rest.tnaot.com:8080/shop/notify/payment/huione
    ras-private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALyl/B0RVu6HJq/M7tJurnnAG38d2HQD/AUjhC5nTj5bsxT6VjzTEvzeTe7c2bPfK9/2IkOK7XjOFwE6JyEXxM1N1kPo2q4xh5rukhtlBSAijx2RebHsRtq6DI+vJgY5BBC0ZcuwR91B9gbVBfbj9isu6q2CgftkHbYFR/Fo8aQrAgMBAAECgYEAoZflD9ksiAIJJ4n6AROCLRRb+VVNdoN7O8OilEU1hsDx88REXrHHkAe05ikT6rn+UUf7LbQxmsuedRSlM/myP1mgcixhtAgIiZdnrXw3qZKqYW4NODHl5nwYWsQXV1paooeMqRO5X2KBAOgvhHkSF63UGDkOGkvo7Suzq24Rl2ECQQDoLCNDr5SvoeiTApXAPt7NXI7eiss+kwbIietjIdhm75it/tz8eb2Nku0+yuoxRKeoYvav9G9CMEcZ3xrKUW/5AkEA0AJXPGvckPPRF/a0u4+gBOSKjmveEFRvozCU76mwaFtGhMvIYslppOYgREOL+rk+k2ZoAgzl8zK78DZOaG2GQwJAbdws16NmpPDlH2MyvyRAw0YP6KgeYj6qEAyLEH58asDnKzYVFXb5xdsHXhYgWS3Wc6xYdIwidVxo2IokoCWG6QJAJhfnpfcS47DjIAJcQuUgpwS7oy1583+jGj2xaNqopdPhbDxtrDm6kSpbymScZAQ8w33DmmyGSC2IYYtwfItiRQJBALCmhfZ73O6wb9+SgWP3wQe/KLMXQftlFQyY69iEQbMfvhZ7V7SXK+M/tFHRWXaswkVZ7LMjMMNDHMMYcuHMwcA=
    alipay-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIF5gfNdMLSWdL7Bnga5zQbiH1G+Gum6N0lNiGvfEgTYeiZUdbWX6qgIErXqJWC65mriu8ZPBJO+GWUbqeNMszrCv7XgkL8sS40S+mSEmY7Fii6KGaWJTGl970C3FK6WZmv0Gez8Iqjt1LcRzrum0N1xzoJfoVZ1Z+E8LjChO0pQIDAQAB
  mpay:
    merc-id: 8888880001571665
    pay-type: Mpay
    ccy: USD
    sign-key: zvyDjCFeAgjjCzZmPbnzAofwXEpJYlwi
    pay-order-url: https://business.bestmpay.com/upg/v2/createWebOrder
    pay-order-url-h5: https://business.bestmpay.com/upg/v2/createWapOrder
    query-order-url: https://business.bestmpay.com/upg/v2/queryOrder
    refund-order-url: https://business.bestmpay.com/upg/v2/refundOrder
    return-url: http://rest.tnaot.com:8080/rest/shop/notify/front/mpay
    notify-url: http://rest.tnaot.com:8080/rest/shop/notify/payment/mpay
    front_fail_url: http://lifetest.tnaot.com/rechargeIndex/prepaidIndex/paymentFail
    front_success_url: http://lifetest.tnaot.com/rechargeIndex/prepaidIndex/paymentSuccess
  pipay:
    merc-id: 102425
    ccy: USD
    sid: 5531
    did: 8085
    pay-order-url: https://onlinepayment-test.pipay.com/starttransaction
    query-order-url: https://onlinepayment-test.pipay.com/rest-api/verifyTransaction
    return-url: http://rest.tnaot.com:8080/rest/shop/notify/front/pipay
    front-fail-url: http://lifetest.tnaot.com/rechargeIndex/prepaidIndex/paymentFail
    front-success-url: http://lifetest.tnaot.com/rechargeIndex/prepaidIndex/paymentSuccess
  wing:
    return_url: http://rest.tnaot.com:8080/rest/shop/notify/front/wing
    username: Koh thmey Technology Co.,Ltd
    rest_api_key: c9aecc2699fcf0135850e81a38d0625576a24c8f595a95f7a73aabe87ded7cab
    biller_code: 5120
    bill_till_rbtn: 0
    sandbox: 1
    pay_url: https://wingsdk.wingmoney.com:334
    front_success_url: http://lifetest.tnaot.com/rechargeIndex/prepaidIndex/paymentSuccess
recharge:
  smart:
    token-url: https://mife.smart.com.kh:8243/token
    recharge-url: https://mife.smart.com.kh:8243/api/etopup/pinless/v1.1/
    user-name: koh.thmey
    password: K04THy%%$$
    evc-number: 98195111
    evc-password: MTIzNDU2
    consumer-key: AJNHhDNoQOZQmWzM9ODjfU8G4mAa
    consumer-secret: GxNcGvvwcmumtIfQFnyS3JQvGLQa
  paygo:
    address: https://api2.paygo24.com/paygoservice.asmx
    username: 46
    password: 123456
  seatel:
    address: http://172.22.188.20:11999/SeatelPayment/pay.jsp
    private-key: 9834a62b4ec7c78a5424932bfdedfd74
    shopid: shoptest
    terminalid: shoptest0001
  metfone:
    host: 10.79.120.2
    port: 8583
    private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALGK137inpjgj+UUPPowP7KMHf6tavJzXKAzFhOsHRvmgd/9hqgv2aJD9OhDoMCGSrp+pOOUx2QtRCaKJ/PV+ucswheOgNjIvK0lW7rFgBsuYn4DU1WnQsv/Xw/EuLwgHzOOlBggdUdwxEO6IrY9kImWWiqUfKtXJ0O9IRE3XgtdAgMBAAECgYBds0UgNkI1tO68m/3CnQxBEyoRazzyUGgmNFAGeeOzAeixaoBS604VEYCDxI1mjnmKC6TCZ5cEC8/X9zo2ukv8LGhQBYFZ2qnPDCIApzb/2MVcBJYkhKeLh14dMO5wTwsGM3Y7YVuMmnYBtsk/GQVj8VI9GjmDqSaEjPxAM/q1EQJBAONMVV87R1WMgsZWtbJbLXrSAZMyVGpyu+BzEJecRWNDGj1rGs+r59f91hfpk6ls4fjoHyMOGV6ZF2DqYRiknSsCQQDH9hiH5qCqykAOx9GzMecZ32EY+8hJAoJ3QMDsMFHtTK4RJkY8wGNuPfl8IN/FhJOU35FQ/o7fSR7N89v22oWXAkEAq0ofHAEkJMga1TULADnN8DzKiw7mpsGH7AFKg7Z0Y/VxlM9eCRpXQWI9MRAJAyjWsijbLiO14qAkChkWyudiuQJAftaQ2uuk8JEYLwf68YLvB89VBQb5Fa682S4+8dL4tOCV7ZTsqq6So6Q2M9Gaf+zHvIBP6iN+tw3nt1Y/KgeVAwJBANK4QLVsAoOL2ayKcXaLFo2is/kLj6uEMp/Dc+uLesyYf/DDyrTD4TyrZDbP8Lt4zxVr360Qoaig+YZe9mnypek=
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCxitd+4p6Y4I/lFDz6MD+yjB3+rWryc1ygMxYTrB0b5oHf/YaoL9miQ/ToQ6DAhkq6fqTjlMdkLUQmiifz1frnLMIXjoDYyLytJVu6xYAbLmJ+A1NVp0LL/18PxLi8IB8zjpQYIHVHcMRDuiK2PZCJlloqlHyrVydDvSERN14LXQIDAQAB
    client-id: kohthmey

bmb:
   front:
       url: 127.0.0.1:8090/bmb/front/
      
