logging:
  config: classpath:logback-dev.xml
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    favicon:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.1.136:3306/mongcent_shop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: dbuser
    password: asdQWE!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      validationQuery: select 'x'
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.1.112
    port: 6379
    password: 123456
    timeout: PT2S
    lettuce:
       pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: PT2S
  data:
    mongodb:
      uri: mongodb://test:123456@192.168.1.112:27017/tnaot
  rabbitmq:
    host: 192.168.1.112
    port: 5672
    username: rabbit
    password: 123456
    publisher-confirms: true
    virtual-host: /
    listener: 
      simple:
        acknowledge-mode: manual
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  type-aliases-package: com.tnaot.**.entity
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    healthcheck:
      enabled: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon: 
  ConnectTimeout: 20000
  ReadTimeout: 20000 
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 3000
management:
  context-path: /listener
  security:
    enabled: false
push:
  firebase:
    service-account: '{ "type": "service_account", "project_id": "earnest-star-187502", "private_key_id": "5d32f4c154242c0a154878b31837a8fa85f40aec", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4uyaKh5LGIPCZ\nVn6KLpef+sqPCg5XbR6gDabn3JjNLowdou50H5B9YsZFkMWfd5rF8JCl2/XfT9Oy\nqhC55du2PX4f3kbO3aaX8hRdjYjxAjEqJJBogwWBj9K5P26WTx9OT6vriqZrdjha\n5OPEN+Ck8ecRoPXqb7JzoGZnzHChMgCmSsHCj1dUlcP6iB3Vw6UUhejzJ1bgOoHZ\nlTNVXUp5dPPten8j0XL5kpIFMfIHLz6UF4O97NPOA4jKD8kqZTJEsWGYgIye6t9R\nJFR/YJSKP9a23XRUb0hqRPQ3Yt+S/RbYRpF5AxWglcSfS3WPJU8nt/S2kgpqYFNg\nyFStjw5fAgMBAAECggEAGWDB519p+doQnkrUUNDHIm07t/GJDYL/erwlZSOtwj0A\nzBl+v2k5WmBgHgfI082EmmjKwQkPesGRXbF2DB6DKULCuZy5sYr1wK4QaixwLFvs\nESlmGqrVQ3qqAlUFMOpnF0UOuJRwTxcLSuwNoP6O2ATQ2l/N04p2GOMSQ8mW4i4A\n6wmXpWbZbyTLKaGwqcPWbjaNNDaOAkFcukkm8QsA5UrEyQsUkwmAiWT+c+WeJTjU\nQM3GSOTr/aiTDiGJuzr5xd2qOGyFnRdE6P3MXiTXNYXQDWMwfE0T8+iez8wNeAZ6\naxy1QznRmYz8CYiilTP4iPZeB1tBNQNqiiXMY3HSgQKBgQDzFSj6XOslT73qbk3a\nvNzQvoiZNFigzfmJSYguq57Awyw5dNuyUGSmIU+uN+t8vfGbg1ITDgUgbJjkyLIQ\n6rwTWkpP/JcxQwnok+64tUaaytuEFM/fBG4/1146V5qBGjQGWSATr9wevV9E6i1x\nPfpVhVe3i21yiQQLOt8w7F1SIQKBgQDCjDBbBEAo+iVB1M36NU1p1whXa3IzLSuP\nia9g/e3fZ0kHjSdGWV2SW/FOzUEXqGQOf9B6wK9IF6SWbokTbIJdgNCmo1vs7r5G\nQHpmIHfh/EmH+pR1WSwTQYHScrk5o2GDtB6AD/W2XEltuPcT+rGu+mtp6ZNkyVNY\n6uQocHlQfwKBgCg10t5/amJ0q2zRLE3HuhtJuVzmfNa029dq830M5KjsYC9s9j6r\n78pPblfaZjjvTr0z3urKAe0YKb6GuHX17oChCfPrS7NZbJUti2rAidpnPiK+Mpio\nqfgjjzHFdghvJjX6nkTDbX0kRFMpDbVS1Es7UIRLKyKsKaAV7/+uyc0hAoGATMxo\nflWEOmjc8krecOo/wAtJ2LCqqTcongYdPG2hTHKKare3DFdUz+UJsjDmhD9OGEcu\ndna/+vaSW2wRIqDQKbcjJtUQAc0RQcxMRSqGCKi+IjayCk0EUCmo5Pmy0uUDJqmg\n7K7gMXfm6LB+oN1y7P8gDfRN4hhzlYNMRAZ6bWMCgYB2HmSHdIVi4lMSPXpqm4LY\nORphroK8dTUr+t70NiKkvcNvgAJtp5LJsYKgPu16i5z+5WKrtmeE9waI24gm/j0g\nNd1sj2BuYNJXqcrF3a6UuTvkd/SOBy2+vLw2oDAJYT0tGhQaMdtOkmvmDs4kx7uR\n9wQIozYWOD2QZqtioBKs8w==\n-----END PRIVATE KEY-----\n", "client_email": "firebase-adminsdk-lgnlk@earnest-star-187502.iam.gserviceaccount.com", "client_id": "103795976778379540002", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-lgnlk%40earnest-star-187502.iam.gserviceaccount.com" }'
    restricted-package-name: com.tnaot.news
    api-key: AIzaSyCaVx7MepT_-xEBH5tMe-ULWDifbIrnM1s
    service-token: AAAAXng1gWw:APA91bHB2Txyc5S8GCzecvYePF-n-TLRvU97zQPeXCKd8lEkqcJwT_6wl60WYqaBY7vu9BIDEkQqWHZ8LQY0-mNFMuKhzonF5yza0yukusVkoz-bVabdzDsd8cOLcx-IMecDdGNtK-Z-
    project-id: earnest-star-187502
    database-url: https://earnest-star-187502.firebaseio.com
  jpush:
    and-app-key: 8a4b4260053b7487e3de4e8f
    and-master-secret: 86ed8517af4a4e16e9c85124
    ios-app-key: 12c6c437e7f0bd35db10a9c7
    ios-master-secret: 6b56e7e47d8d84fd4c0a52b1
    is-pro: false
  huawei:
    token-url: https://login.cloud.huawei.com/oauth2/v2/token
    push-url: https://api.push.hicloud.com/pushsend.do
    app-id: 100503013
    app-secret: 1d9f5e4151900bec1644bb88facb5cdb
    package-name: com.tnaot.news
    sha256: 09:BA:6F:4A:65:21:A6:17:DC:29:1A:B4:23:D4:9B:8F:2B:F6:59:C7:54:8F:E5:1E:1A:D7:DC:AC:40:34:D3:EB
  oppo:
    app-id: 3718625
    app-key: 0d0926283eb64c87b631f70858956ea6
    app-secret: 605ee815c7594a28a4dceb04cb8147ec
    master-secrect: c4a760be53dc4ab3832b34585b554956
    package-name: com.tnaot.news
  xiaomi:
    app-key: 5461789345824
    app-secret: 5OhyJI8FZLtUgoZBMC6GRA==
    app-id: 2882303761517893824
    package-name: com.tnaot.news
  vivo:
    app-key: 5461789345824
    app-secret: 5OhyJI8FZLtUgoZBMC6GRA==
    app-id: 2882303761517893824